// <auto-generated />
using System;
using AtoCashAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtoCashAPI.Migrations
{
    [DbContext(typeof(AtoCashDbContext))]
    partial class AtoCashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtoCashAPI.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AtoCashAPI.Models.ApprovalGroup", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("ApprovalGroupCode")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ApprovalGroupDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalGroups");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ApprovalLevel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Level")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("LevelDesc")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalLevels");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ApprovalRoleMap", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalGroupId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalLevelId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("JobRoleId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalGroupId");

                    b.HasIndex("ApprovalLevelId");

                    b.HasIndex("JobRoleId");

                    b.ToTable("ApprovalRoleMaps");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ApprovalStatusType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusDesc")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalStatusTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Bank", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BankDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("AtoCashAPI.Models.BusinessType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BusinessTypeDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("BusinessTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("BusinessTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.BusinessUnit", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BusinessDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("BusinessTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CostCenterId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ClaimApprovalStatusTracker", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalGroupId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalLevelId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JobRoleId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("PettyCashRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReqDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalLevelId");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("PettyCashRequestId");

                    b.HasIndex("ProjManagerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("ClaimApprovalStatusTrackers");
                });

            modelBuilder.Entity("AtoCashAPI.Models.CostCenter", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CostCenterCode")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CostCenterDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("AtoCashAPI.Models.CurrencyType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("CurrencyTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.DisbursementsAndClaimsMaster", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("varchar(150)");

                    b.Property<double?>("AmountToCredit")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmountToWallet")
                        .HasColumnType("double precision");

                    b.Property<int?>("ApprovalStatusId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<double?>("ClaimAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int?>("CostCenterId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("CurrencyTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ExpenseReimburseReqId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsSettledAmountCredited")
                        .HasColumnType("boolean");

                    b.Property<int?>("PettyCashRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecordDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RequestTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettlementAccount")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SettlementBankCard")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SettlementComment")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpenseReimburseReqId");

                    b.HasIndex("PettyCashRequestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("DisbursementsAndClaimsMasters");
                });

            modelBuilder.Entity("AtoCashAPI.Models.EmpCurrentPettyCashBalance", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<double?>("CashOnHand")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<double?>("CurBalance")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<double?>("MaxPettyCashLimit")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmpCurrentPettyCashBalances");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Employee", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("BankCardNo")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BankId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrencyTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DOB")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DOJ")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("EmploymentTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IBAN")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalID")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AtoCashAPI.Models.EmployeeExtendedInfo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("JobRoleId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalGroupId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("EmployeeExtendedInfos");
                });

            modelBuilder.Entity("AtoCashAPI.Models.EmploymentType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("EmpJobTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmpJobTypeDesc")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseCategory", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("ExpenseCategoryDesc")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ExpenseCategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsBusinessCategory")
                        .HasColumnType("boolean");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseReimburseRequest", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrencyTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpReimReqDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpenseReportTitle")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsStoreReq")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalClaimAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("ExpenseReimburseRequests");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseReimburseStatusTracker", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalLevelId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CurrencyTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpReimReqDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpenseReimburseRequestId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("JobRoleId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ProjManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalClaimAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalGroupId");

                    b.HasIndex("ApprovalLevelId");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpenseReimburseRequestId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("ProjManagerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("ExpenseReimburseStatusTrackers");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseSubClaim", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<int?>("CostCenterId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DocumentIDs")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpNoOfDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpStrtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpenseCategoryId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<double?>("ExpenseReimbClaimAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int?>("ExpenseReimburseRequestId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ExpenseTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InvoiceDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsStoreReq")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVAT")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<float>("Tax")
                        .HasColumnType("real");

                    b.Property<double?>("TaxAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<string>("TaxNo")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ExpenseReimburseRequestId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("ExpenseSubClaims");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ExpenseCategoryId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ExpenseTypeDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ExpenseTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("GeneralLedgerId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("GeneralLedgerId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.FileDocument", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("ActualFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileDocuments");
                });

            modelBuilder.Entity("AtoCashAPI.Models.GeneralLedger", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("GeneralLedgerAccountName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("GeneralLedgerAccountNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("GeneralLedger");
                });

            modelBuilder.Entity("AtoCashAPI.Models.JobRole", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("JobRoleCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JobRoleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("MaxPettyCashAllowed")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Location", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<decimal?>("Lattitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("LocationDesc")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AtoCashAPI.Models.PettyCashRequest", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CashReqDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrencyTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<double?>("PettyClaimAmount")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<string>("PettyClaimRequestDesc")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("PettyCashRequests");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Project", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("CostCenterId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("ProjManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("ProjManagerId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ProjectManagement", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectManagements");
                });

            modelBuilder.Entity("AtoCashAPI.Models.RequestType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequestTypeDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.StatusType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.ToTable("StatusTypes");
                });

            modelBuilder.Entity("AtoCashAPI.Models.SubProject", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ProjectId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("SubProjectDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SubProjectName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SubProjects");
                });

            modelBuilder.Entity("AtoCashAPI.Models.TravelApprovalRequest", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CostCenterId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReqRaisedDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravelEndDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TravelPurpose")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("TravelStartDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("TravelApprovalRequests");
                });

            modelBuilder.Entity("AtoCashAPI.Models.TravelApprovalStatusTracker", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalGroupId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalLevelId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalStatusTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JobRoleId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ProjManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReqDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TravelApprovalRequestId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravelEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TravelStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalLevelId");

                    b.HasIndex("ApprovalStatusTypeId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("ProjManagerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("TravelApprovalRequestId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("TravelApprovalStatusTrackers");
                });

            modelBuilder.Entity("AtoCashAPI.Models.VATRate", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<float>("VATPercentage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("VATRates");
                });

            modelBuilder.Entity("AtoCashAPI.Models.WorkTask", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("SubProjectId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("TaskDesc")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubProjectId");

                    b.ToTable("WorkTasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AtoCashAPI.Models.ApprovalRoleMap", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalGroup", "ApprovalGroup")
                        .WithMany()
                        .HasForeignKey("ApprovalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ApprovalLevel", "ApprovalLevel")
                        .WithMany()
                        .HasForeignKey("ApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalGroup");

                    b.Navigation("ApprovalLevel");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Bank", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.BusinessType", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.BusinessUnit", b =>
                {
                    b.HasOne("AtoCashAPI.Models.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");

                    b.Navigation("CostCenter");

                    b.Navigation("Location");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ClaimApprovalStatusTracker", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalLevel", "ApprovalLevel")
                        .WithMany()
                        .HasForeignKey("ApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.PettyCashRequest", "PettyCashRequest")
                        .WithMany()
                        .HasForeignKey("PettyCashRequestId");

                    b.HasOne("AtoCashAPI.Models.Employee", "ProjManager")
                        .WithMany()
                        .HasForeignKey("ProjManagerId");

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalLevel");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Employee");

                    b.Navigation("JobRole");

                    b.Navigation("PettyCashRequest");

                    b.Navigation("ProjManager");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.CostCenter", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.CurrencyType", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.DisbursementsAndClaimsMaster", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ExpenseReimburseRequest", "ExpenseReimburseRequest")
                        .WithMany()
                        .HasForeignKey("ExpenseReimburseReqId");

                    b.HasOne("AtoCashAPI.Models.PettyCashRequest", "PettyCashRequest")
                        .WithMany()
                        .HasForeignKey("PettyCashRequestId");

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CostCenter");

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("ExpenseReimburseRequest");

                    b.Navigation("PettyCashRequest");

                    b.Navigation("Project");

                    b.Navigation("RequestType");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.EmpCurrentPettyCashBalance", b =>
                {
                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Employee", b =>
                {
                    b.HasOne("AtoCashAPI.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");

                    b.HasOne("AtoCashAPI.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("CurrencyType");

                    b.Navigation("EmploymentType");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.EmployeeExtendedInfo", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalGroup", "ApprovalGroup")
                        .WithMany()
                        .HasForeignKey("ApprovalGroupId");

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalGroup");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Employee");

                    b.Navigation("JobRole");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseCategory", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseReimburseRequest", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId");

                    b.HasOne("AtoCashAPI.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CostCenter");

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseReimburseStatusTracker", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalGroup", "ApprovalGroup")
                        .WithMany()
                        .HasForeignKey("ApprovalGroupId");

                    b.HasOne("AtoCashAPI.Models.ApprovalLevel", "ApprovalLevel")
                        .WithMany()
                        .HasForeignKey("ApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ExpenseReimburseRequest", "ExpenseReimburseRequest")
                        .WithMany()
                        .HasForeignKey("ExpenseReimburseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "ProjManager")
                        .WithMany()
                        .HasForeignKey("ProjManagerId");

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalGroup");

                    b.Navigation("ApprovalLevel");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("ExpenseReimburseRequest");

                    b.Navigation("JobRole");

                    b.Navigation("ProjManager");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseSubClaim", b =>
                {
                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ExpenseReimburseRequest", "ExpenseReimburseRequest")
                        .WithMany()
                        .HasForeignKey("ExpenseReimburseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CostCenter");

                    b.Navigation("Employee");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ExpenseReimburseRequest");

                    b.Navigation("ExpenseType");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ExpenseType", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.GeneralLedger", "GeneralLedger")
                        .WithMany()
                        .HasForeignKey("GeneralLedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("GeneralLedger");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.GeneralLedger", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Location", b =>
                {
                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.PettyCashRequest", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId");

                    b.HasOne("AtoCashAPI.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CostCenter");

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.Project", b =>
                {
                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostCenter");

                    b.Navigation("ProjectManager");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("AtoCashAPI.Models.ProjectManagement", b =>
                {
                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AtoCashAPI.Models.SubProject", b =>
                {
                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AtoCashAPI.Models.TravelApprovalRequest", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("CostCenter");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.TravelApprovalStatusTracker", b =>
                {
                    b.HasOne("AtoCashAPI.Models.ApprovalLevel", "ApprovalLevel")
                        .WithMany()
                        .HasForeignKey("ApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.ApprovalStatusType", "ApprovalStatusType")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("AtoCashAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.Employee", "ProjManager")
                        .WithMany()
                        .HasForeignKey("ProjManagerId");

                    b.HasOne("AtoCashAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId");

                    b.HasOne("AtoCashAPI.Models.TravelApprovalRequest", "TravelApprovalRequest")
                        .WithMany()
                        .HasForeignKey("TravelApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Models.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId");

                    b.Navigation("ApprovalLevel");

                    b.Navigation("ApprovalStatusType");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Employee");

                    b.Navigation("JobRole");

                    b.Navigation("ProjManager");

                    b.Navigation("Project");

                    b.Navigation("SubProject");

                    b.Navigation("TravelApprovalRequest");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AtoCashAPI.Models.WorkTask", b =>
                {
                    b.HasOne("AtoCashAPI.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AtoCashAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AtoCashAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoCashAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AtoCashAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
